services:
  - type: web
    name: ctr-mapper
    runtime: docker
    dockerfilePath: ./webapp/Dockerfile
    dockerContext: ./webapp
    plan: free
    envVars:
      - key: PORT
        value: 10000
